### ISSUE TITLE
Installer: Warning value template

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/yform_spam_protection#19]
`Warning: yform template value.spam_protection.tpl.php not found in redaxo/src/addons/yform/lib/yform.php on line 482`

Warum auch immer?

**Comment by olien** [comment]
Ich bekomme das:

`Warning: yform template value.spam_protection.tpl.php not found in redaxo/src/addons/yform/lib/yform.php on line 482
Warning: include(): Filename cannot be empty in redaxo/src/addons/yform/lib/yform/value/abstract.php on line 144
Warning: include(): Failed opening '' for inclusion (include_path='.:/Applications/MAMP/bin/php/php7.3.1/lib/php') in redaxo/src/addons/yform/lib/yform/value/abstract.php on line 144`

**Comment by alexplusde** [comment]
Das ist mir nicht erklärlich. Github-Version oder Installer-Version?

**Comment by olien** [comment]
Aus dem Installer. ich versuche gleich gerne mal die GH Version

**Comment by olien** [comment]
Grad getestet. Die Warnings kommen auch bei der GitHub Version.

**Comment by olien** [comment]
Scheint aber trotzdem zu funktionieren (gibt es einen guten Weg das zu testen?

**Comment by alexplusde** [comment]
Ich versuche, mich am Sonntag darum zu kümmern.

**Comment by olien** [comment]
ok. meinetwegen eilt es nicht... (danke)

**Comment by skerbis** [comment]
24.06.2020 23:18:17	Warning	yform template value.spam_protection.tpl.php not found	
redaxo/src/addons/yform/lib/yform.php
482

Das selbe hier

**Comment by alexplusde** [comment]
Kann das evtl jemand fixen? Ich verstehe nicht, warum das kommt.

**Comment by TobiasKrais** [comment]
Ist schon mal getestet worden, ob dieser Fehler im Zusammenhang mit einem anderen Addon auftaucht? Den Fehler kann ich auch nicht nachstellen.

**Comment by alxndr-w** [comment]
#29

**Comment by marcohanke** [comment]
@alxndr-w meinst du das hängt zusammen?

**Comment by alxndr-w** [comment]
Sorry, gerade 150 Issues aus Lesezeichen, Benachrichtigungen und so entfernt, da hab ich das falsch in Zusammenhang gebracht. Bitte weitergehen.

**Comment by Clindbergh** [comment]
Fehler tritt bei mir mit folgenden AddOns auf
Name | Version | Informationen | 
-- | -- | -- 
  | backup | 2.6.1 | Hilfe backup 
  | be_style | 2.11.0 | Hilfe be_style 
  | customizer | 2.11.0 | Hilfe customizer 
  | redaxo | 2.11.0 | Hilfe redaxo 
  | bloecks | 3.0.0 | Hilfe bloecks 
  | cutncopy | 3.0.0 | Hilfe cutncopy 
  | dragndrop | 3.0.0 | Hilfe dragndrop 
  | status | 3.0.0 | Hilfe status 
  | cronjob | 2.7.1 | Hilfe cronjob 
  | debug | 1.0.0 | Hilfe debug 
  | developer | 3.9.0 | Hilfe developer 
  | install | 2.8.0 | Hilfe install 
  | mblock | 3.1.0 | Hilfe mblock 
  | media_manager | 2.10.0 | Hilfe media_manager 
  | mediapool | 2.9.0 | Hilfe mediapool 
  | metainfo | 2.7.2 | Hilfe metainfo 
  | mform | 5.3.1 | Hilfe mform 
  | docs | 1.0 | Hilfe docs 
  | modulsammlung | 4.14.0 | Hilfe modulsammlung 
  | documentation | 1.0 | Hilfe documentation 
  | phpmailer | 2.9.0 | Hilfe phpmailer 
  | project | dev | Hilfe project 
  | quick_navigation | 3.7.2 | Hilfe quick_navigation 
  | redactor2 | 4.0.3 | Hilfe redactor2 
  | slice_publish_date |   | Hilfe slice_publish_date 
  | structure | 2.11.0 | Hilfe structure 
  | content | 2.11.0 | Hilfe content 
  | history | 2.11.0 | Hilfe history 
  | version | 2.11.0 | Hilfe version 
  | twoeg | 0.3-alpha | Hilfe twoeg 
  | users | 2.7.0 | Hilfe users 
  | xcore | 1.1.4 | Hilfe xcore 
  | yform | 3.4.1 | Hilfe yform 
  | email | 3.4.1 | Hilfe email 
  | manager | 3.4.1 | Hilfe manager 
  | rest | 3.4.1 | Hilfe rest 
  | tools | 3.4.1 | Hilfe tools 
  | yform_spam_protection | 1.0.5 | Hilfe yform_spam_protection 
  | yrewrite | 2.6

**Comment by alxndr-w** [comment]
Wird der lib-Ordner vlt. früher geladen und die YForm-Defintionen als die Fragmente beim Installieren?

**Comment by alxndr-w** [comment]
Scheinbar gibt es hier kein Problem mehr.
