### ISSUE TITLE
Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/yform_spam_protection#29]
In meinem Redaxo Error Log finde ich folgenden Eintrag:
Warning | A non-numeric value encountered | redaxo/src/addons/yform_spam_protection/lib/yform/value/spam_protection.php | 42

Ein Szenario zum Nachstellen des Fehler ist mir nicht bekannt. Zudem trat der Fehler nur einmalig auf.

**Comment by marcohanke** [comment]
Ich habs mir gerade mal angesehen, scheinbar hattest du im Backend unter Session-Timer versehentlich was anderes als Zahlen mit drin. Könnte man umgehen indem man die Inputs auf Intger prüft. Hast du Lust das zu machen?

**Comment by TobiasKrais** [comment]
Im Backend sind nur Zahlen drin und auch drin gewesen. Der Fehler ist heute um 4 Uhr Nachts aufgetreten - davor und danach nicht mehr. Bringt das Umstellen ein numerisches Feld sicher die Lösung?

**Comment by marcohanke** [comment]
Mhh, dann liegt es wohl nicht am Input (der aber trotzdem abgefangen werden könnte) sondern an $session_timestamp oder der microtime. `$session_timestamp` ist bei mir 1606292621,1977 also nicht numeric, aber dann müsste der Fehler eigentlich immer auftauchen. Da bin ich leider erstmal raus.

**Comment by alxndr-w** [comment]
Hat das was mit den Bot-Besuchen von SEO-Dings zu tun und weil da ja Fehler bei den SESSIONS auf falsch konfigurierten Apache-Servern auftreten? (Siehe Slack-Diskussion neulich)

**Comment by marcohanke** [comment]
Bei mir kam der Fehler nach einem FormSubmit und wenn es mit falsch konfigurierten Apache-Servern zusammenhängt müsste da die microtime falsch ankommen oder? Was leider immer noch nicht erklärt warum es nur einmalig kam.
@TobiasKrais Probier doch mal dein Formular so auszufüllen, dass spam_protection anschlägt.

**Comment by TobiasKrais** [comment]
Habs probiert. Spamschutz schlägt an, aber kein weiterer Eintrag im Fehlerlog. 

@alxndr-w: ist das dann überhaupt ein Fehler? Macht es dann Sinn das abzufangen? Wenn ja, dann müsste man doch einfach noch prüfen, ob eine Session existiert, oder?

**Comment by alxndr-w** [comment]
Keine Ahnung, im Zweifel entscheidet der Lead des Addons.

**Comment by marcohanke** [comment]
@alxndr-w Du darfst das gerne wieder übernehmen. Ich bin hier zum Lead (gemacht worden) gekommen. Weil du seinerzeit alles hingeworfen hast, ich reiße mich nicht drum.
@TobiasKrais Ich hab die Slack Diskussion nicht finden können und weiß nicht um was es geht.
Die Inputs zu prüfen würde (unabhängig von deinem Fehler) Sinn machen. Alles andere kann ich hier nicht nachvollziehen.

**Comment by TobiasKrais** [comment]
@alxndr-w: ich hab die Diskussion auch nicht verfolgt. weißt du da noch was genaueres? Dann kann ich den Fehler auch richtig anpacken.

**Comment by alxndr-w** [comment]
@marcohanke Danke, ich verzichte. Ich hatte nicht den Eindruck, dass du unfreiwillig den Lead übernehmen musstest. Es bleibt ganz deine Entscheidung.

**Comment by marcohanke** [comment]
Wie auch immer dieser Eindruck entstanden ist ...
Naja, egal, viel Spaß weiterhin auf jeden Fall @alxndr-w 
Da du hier keine weitern Infos zur Erwähnten Slack Diskussion geben möchtest und weder Ich noch @TobiasKrais wissen um was es geht können wir hier nur weiter rumraten.
@TobiasKrais Ich würde sagen du beobachtest noch ein paar Tage ob das ganze noch mal auftaucht.

**Comment by TobiasKrais** [comment]
OK. Fehler ist gefunden und behoben: https://github.com/FriendsOfREDAXO/yform_spam_protection/pull/30

Den Issue schließe ich schon mal, dann muss @marcohanke das nicht machen.

**Comment by alxndr-w** [comment]
@TobiasKrais schreib `close #29` in deinen PR #30 und dann schließt es #29 automatisch

**Comment by TobiasKrais** [comment]
Ah, das ist ja ein cooles Feature. Danke für den Hinweis!
