### ISSUE TITLE
Nach Einspielen eines Backups muss die Tabelle neu angelegt werden 

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/yform_spam_protection#31]
Andernfalls kommt es im Frontend direkt zu einem Whooops.

**Comment by marcohanke** [comment]
Du meinst wenn die temp Tabelle nicht mit gesichert wurde? Ich hab' keine Idee wie ich das lösen sollte. Bekommt yform_spam_protection mit wenn ein Backup eingespielt wird?

**Comment by alxndr-w** [comment]
Gelöst werden könnte das über ein try/catch: Wenn der Zugriff auf die Tabelle fehlschlägt, dann die Tabelle frisch anlegen und erneut versuchen.

**Comment by alxndr-w** [comment]
https://github.com/redaxo/redaxo/issues/4391 ist der bessere Ansatz und es scheint laut Slack auch niemanden außer mir erwischt zu haben mit diesem Fehler.
