### ISSUE TITLE
PHP 8.X verhindert Installation

### ISSUE THREAD

**Issue by ritzfritz** [FriendsOfREDAXO/yform_spam_protection#33]
Bitte bitte erweitern.

**Comment by skerbis** [comment]
@ritzfritz hier ändern und PR nach erfolgreichem Test einreichen https://github.com/FriendsOfREDAXO/yform_spam_protection/blob/c7ba57a8c092e8ffec49700bb9f92f19b2e6893d/package.yml#L11

**Comment by marcohanke** [comment]
Servus @ritzfritz Könntest du das kurz übernehmen?

**Comment by skerbis** [comment]
@marcohanke es liegt doch schon ein PR vor?
