### ISSUE TITLE
Docs: Hinweis zu form_name

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/yform_spam_protection#36]
> Schau mal, ob du den form_name objparam gesetzt hast. Sonst passiert genau das, was Marco gerade geschrieben hat vermute ich.

via @ynamite @claudihey @pschuchmann @marcohanke

**Comment by claudihey** [comment]
Ja, lag an form_name... ;-)

**Comment by alxndr-w** [comment]
Könnte ja jemand die README anpassen....
