### ISSUE TITLE
Kein Spamschutz im classic Mode

### ISSUE THREAD

**Issue by NGWNGW** [FriendsOfREDAXO/yform_spam_protection#37]
Der Spamschutz greift nicht im "classic" Modus, da kein Template dafür vorhanden ist.
Abhilfe schafft "Template von /ytemplates/bootstrap nach /ytemplates/classic kopieren".

**Comment by marcohanke** [comment]
Servus @NGWNGW willst du das gerade als PR hochladen?

**Comment by alxndr-w** [comment]
Finde die Lösung eher Mittel. Man hätte auch bei der Template-Definition `classic,bootstrap` definieren können, dann wäre als Fallback alles da.

Jetzt muss man den Code doppelt pflegen.

**Comment by alxndr-w** [comment]
Hä?! Ich kann doch nicht einen PR an deinem Formular-Code machen. 🤷‍♂️

Macht doch den PR einfach wieder rückgängig.

**Comment by alxndr-w** [comment]
https://github.com/yakamara/redaxo_yform/blob/master/docs/formbuilder.md#ein-eigenes-template--framework-f%C3%BCr-formularcode-verwenden

`objparam|form_ytemplate|classic,bootstrap`

**Comment by alxndr-w** [comment]
Jetzt ist das Kind schon in den Brunnen gefallen - das Addon ist so über Monate veröffentlicht. Das überflüssige Classic-Template wieder raus zu nehmen wäre nicht mehr rückwärtskompatibel. Von mir aus kann das Issue zu.

**Comment by alxndr-w** [comment]
@omphteliba kannst du hier zumachen?
