### ISSUE TITLE
Akismet

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/yform_spam_protection#43]
Wir setzen den Dienst "Akismet" von Wordpress, recht erfolgreich gegen Formular-Spam ein. 

https://akismet.com/

Vllt wär das eine sinnvolle Option für die yform_spam_protection.

**Comment by alxndr-w** [comment]
Ich hatte Pläne für Drittanbieter und Ansätze, für die sich aber leider niemand als Auftraggeber gefunden hat. 

Akismet ist durch die DSGVO kritisch zu betrachten, es sollte nie direkt aktiviert sein. Vorher gibt's aber andere interessante Lösungen.

Wenn du dich am Addon beteiligen wollen würdest, gib gerne Bescheid.

**Comment by alxndr-w** [comment]
Siehe #1 #5 #8 #10

**Comment by omphteliba** [comment]
Alles klar. Ich schau mir die Issues mal, kann aber nichts versprechen.
