### ISSUE TITLE
IP Whitelist

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/yform_spam_protection#45]
Ich fänd eine IP-Whitelist ganz praktisch, um die Kollegen die Seiten mit Formularen bauen und testen nicht immer wieder entsperren zu müssen. Oder meinst Du das ist dann eher ein Config-Problem?

**Comment by alxndr-w** [comment]
Klar, übers Intranet bei festen IPs oder bei Anmeldung im Backend die Überprüfung ausschalten. Müsste mit wenig Aufwand erledigt sein.

**Comment by alxndr-w** [comment]
@omphteliba hier kann auch zu. Das nächste mal im PR ganz am Anfang in den ersten Kommentar reinschreiben `close #issuenummer` also hier `close #45`, dann wäre dieses Issue auch automatisch zu.
