### ISSUE TITLE
Eingeloggte Backend-Benutzer werden _nicht_ ignoriert

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/yform_spam_protection#56]
Obwohl das Ignorieren aktiviert ist, wird man als Backend-User dennoch als Spam erkannt.

**Comment by tbaddade** [comment]
Anscheinend wird man ständig geblockt.
Auch nach 15 Minuten "Wartezeit" wird man weiterhin als Spam angesehen.

**Comment by alxndr-w** [comment]
Am besten das Log aktivieren und schauen, warum diese Prüfung fehlschlägt: https://github.com/FriendsOfREDAXO/yform_spam_protection/blob/87c27e62b975876528b7ef17575511205add95b2/lib/yform/value/spam_protection.php#L30

**Comment by tbaddade** [comment]
> Am besten das Log aktivieren

Welches Log muss aktiviert werden?

**Comment by alxndr-w** [comment]
Da gibt's einen 4. Parameter am Value, den auf 1 setzen, dann erhältst du eine Ausgabe im Frontend, was wie geprüft wurde.

**Comment by alxndr-w** [comment]
Wenn's geht, gleich mit Version 2.0 testen
