### ISSUE TITLE
Fatal error bei Update auf 2.0-beta3

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/yform_spam_protection#61]
Nachfolgender Fehler kommt beim Update von Version 1.2.1 auf Version 2.0-beta3
**TypeError:** rex_yform_manager_table_api::importTablesets(): Argument #1 ($tableset_content) must be of type string, null given, called in /www/htdocs/w019d09f/staging.inotec-gmbh.com/redaxo/src/addons/.new.yform_spam_protection/update.php on line 3
**File:** redaxo/src/addons/yform/plugins/manager/lib/yform/manager/table/api.php
**Line:** 92

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                       | Line     |
| -------------------------------------------- | ---------------------------------------------------------- | -------- |
| rex_yform_manager_table_api::importTablesets | redaxo/src/addons/.new.yform_spam_protection/update.php    | 3        |
| require                                      | redaxo/src/core/lib/packages/package.php                   | 280      |
| rex_package->includeFile                     | redaxo/src/addons/install/lib/package/package_update.php   | 63       |
| rex_install_package_update->doAction         | redaxo/src/addons/install/lib/package/package_download.php | 44       |
| rex_install_package_download->run            | redaxo/src/addons/install/lib/api/api_package_update.php   | 21       |
| rex_api_install_package_update->execute      | redaxo/src/core/lib/api_function.php                       | 180      |
| rex_api_function::handleCall                 | redaxo/src/core/backend.php                                | 234      |
| require                                      | redaxo/src/core/boot.php                                   | 143      |
| require                                      | redaxo/index.php                                           | 9        |

</details>
<details>
<summary>System report (REDAXO 5.13.3, PHP 8.1.3, MySQL 5.7.37)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.3     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.1.3      |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.37 |
| Character set | utf8         |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |               |
| ------------: | :------------ |
|       Browser | Firefox/101.0 |
|      Protocol | HTTP/2.0      |
|         HTTPS | yes           |

| Packages                                               |            |
| -----------------------------------------------------: | :--------- |
|                                                 backup | 2.8.1      |
|                                            be_branding | 1.7        |
|                                               be_style | 3.0.2      |
|                                    be_style/customizer | 3.0.2      |
|                                        be_style/redaxo | 3.0.2      |
|                                                cronjob | 2.8.2      |
|                                            d2u_address | 1.2.2      |
|                                             d2u_helper | 1.9.3      |
|                          d2u_helper/translation_helper | 1.9.3      |
|                                               d2u_jobs | 1.2.3      |
|                                            d2u_linkbox | 1.2.5      |
|                                          d2u_machinery | 1.3.6      |
|                                d2u_machinery/equipment | 1.3.6      |
| d2u_machinery/machine_construction_equipment_extension | 1.3.6      |
|               d2u_machinery/machine_features_extension | 1.3.6      |
|             d2u_machinery/machine_usage_area_extension | 1.3.6      |
|                                             d2u_videos | 1.0.9      |
|                                        emailobfuscator | 3.0.0      |
|                                            inotec-city | 1.0.0      |
|                                                install | 2.9.3      |
|                                            maintenance | 2.8.1      |
|                                          media_manager | 2.12.3     |
|                                              mediapool | 2.11.3     |
|                                               metainfo | 2.8.5      |
|                                        multinewsletter | 3.2.9      |
|                                               osmproxy | 1.6.0      |
|                                              phpmailer | 2.11.2     |
|                                                project | dev        |
|                                              search_it | 6.9.0      |
|                                 search_it/autocomplete | 6.9.0      |
|                                search_it/documentation | 6.9.0      |
|                                    search_it/plaintext | 6.9.0      |
|                                        search_it/stats | 6.9.0      |
|                                                  sprog | 1.3.0      |
|                                             statistics | 2.2.0      |
|                                       statistics/media | 2.2.0      |
|                                              structure | 2.13.3     |
|                                      structure/content | 2.13.3     |
|                                               tinymce5 | 1.2.15     |
|                                               uploader | 2.3.0      |
|                                                    url | 2.0.1      |
|                                                  users | 2.8.2      |
|                                                  yform | 4.0.2      |
|                                            yform/email | 4.0.2      |
|                                          yform/manager | 4.0.2      |
|                                  yform_spam_protection | 1.2.1      |
|                                               yrewrite | 2.8.3      |

</details>

**Comment by alxndr-w** [comment]
Seltsam. Ich schaue Mal danach.

**Comment by alxndr-w** [comment]
Sieht so aus, als ob es genau das war. Würde zwar erwarten, dass das REDAXO im Update-Prozess richtig behandelt, vielleicht gibt's dafür auch eine separate Methode - aber für den Moment ist es gelöst und eine neue Version im Installer.

Bitte auf keinen Fall produktiv einsetzen, ich habe sie selbst noch nicht produktiv im Einsatz.

**Comment by TobiasKrais** [comment]
Danke! Funktioniert jetzt einwandfrei!
