### ISSUE TITLE
Nonce ergänzen wenn entsprechende CSP Header gesetzt werden

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/yform_spam_protection#66]
Im Moment noch nicht möglich, aber wenn CSP Header gesetzt werden und script und style beim Direktaufruf verboten sind, müsste eine Nonce ergänzt werden.

Sobald der PR hier durch ist, könnte man es hier ergänzen 

https://github.com/redaxo/redaxo/pull/5510

**Comment by alxndr-w** [comment]
#67 67
