### ISSUE TITLE
Template wird bei Update gelöscht

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/yform_spam_protection#68]
Hallo Alex,

ich habe gerade bei einem Projekt das AddOn von 1.2.0 auf 1.2.3 gehievt, was am Ende in einem Whoops-Screen endete sobald ich eine Seite mit einem yForm-Formular aufrufe.

Problem ist gewesen, dass ich unter `/yform_spam_protection/ytemplates/` in Version 1.2.0 ein eigenes Template gespeichert hatte, was dann nach dem Update verschwunden war und somit den Whoops-Screen triggerte ("Path cannot be empty").
Lösung war: Einfach mein yTemplate von der Festplatte via FTP wieder in den Ordner gelegt => Whoops weg, yForm-Seite läuft.

Es wäre cool, wenn zukünftig eigene Ergänzungen im yTemplates-Ordner bei einem Update erhalten bleiben. :) 

Danke und Gruß,
Stefan

**Affected versions / Verwendete Versionen**

REDAXO: 5.15.1
PHP: 8.1.25
Database: MySQL 5.7.42
Browser: Chrome (aktuell)
AddOns: yForm 4.1.1 / yForm Spam Protection 1.2.3

**Comment by alxndr-w** [comment]
Sorry, so ist es nicht gedacht. Eigene Überschreibungen ins project-Addon bzw eigenes Template anlegen. Du kannst auch nur Ergänzungen in einem eigenen Template auslagern und notieren.

**Comment by dpf-dd** [comment]
Ähm, ich nutze ja ein eigenes yTemplate und das liegt im Theme-Ordner unter `/theme/private/ytemplates/`
Nur leider wird das offenbar vom Spam-Protection-AddOn ignoriert - genau deswegen habe ich es ja nochmal in den AddOn-Ordner kopiert...

**Comment by alxndr-w** [comment]
Dann scheint es ein Theme-Bug zu sein. Dein Theme muss aber auch im Zweifel registriert werden - ich weiß nicht, ob das bei Theme automatisch der Fall ist. Das wäre dann nicht mehr ein Problem dieses Addons. Mehr kann ich dazu leider nicht sagen. :/

**Comment by dpf-dd** [comment]
OK, dann geht es hier weiter... :)
https://github.com/FriendsOfREDAXO/theme/issues/43

**Comment by alxndr-w** [comment]
Prima. Du kannst auch als Fallback mehrere Templates am objparam definieren:

`deinytemplate,bootstrap`
