### ISSUE TITLE
Recaptcha als Plugin entfernen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/yform_spam_protection#69]
**Feature description / Feature Beschreibung**
https://github.com/FriendsOfREDAXO/yform_spam_protection/tree/main/plugins/recaptcha

Von meiner Seite aus darf das gern ausgelagert werden in ein anderes Addon. Auch wenn ich es damals hier aufgenommen habe aus Kompatibilitätsgründen - ich halte Recaptcha nicht für eine gute Empfehlung hier, solange das Honeypot-Feld so gut Spam standhält.

**Comment by skerbis** [comment]
ja von mir aus kann es weg, ist eh aus meiner Sicht ein Dsgvo problem
