### ISSUE TITLE
Data too long for column 'was_blocked'

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/yform_spam_protection#70]
Wollte eben ein via Backup-AddOn erstellten Dum lokal in eine MariaDB importieren und erhalten diesen Fehler.

**Fehler**

Data too long for column 'was_blocked' at row 1

**Values for row 1**
```(1234123412,'','2022-01-14 16:38:31','0'),```

**Affected versions / Verwendete Versionen**

yform_spam_protection: 1.2.0

**Comment by alxndr-w** [comment]
Hier wird bit als Typ verlangt, kann es sein, dass das Value im Backup fälschlicherweise String ist?

https://github.com/FriendsOfREDAXO/yform_spam_protection/blob/57dfa1f092eef591726f3e1e5a710cd519127623/install.php#L7

Den Datentyp können wir natürlich ändern in int(1) oder was kompatibler wäre.

**Comment by alxndr-w** [comment]
Dieses Problem scheint sonst niemandem aufzufallen, wie kann das sein?
