### ISSUE TITLE
Entwickler bei Spam-Welle informieren

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yform_spam_protection#9]
Wenn über einen fixen Zeitraum, bspw. 10 Minuten, fehlgeschlagene Validierungen - also Spam - sich häuft, dann den Entwickler darüber informieren, sodass dieser evtl. vor dem Kunden Bescheid weiß und die Einstellungen zeitweise verschärfen kann.

- [x] Einstellung bieten
- [ ] Stille YForm-Mail versenden
- [ ] Docs

**Comment by alexplusde** [comment]
https://friendsofredaxo.github.io/tricks/addons/yform/send_hidden_mail

**Comment by alexplusde** [comment]
@191977 wäre das was für dich=

**Comment by 191977** [comment]
Ja denke schon. Ich schaue es mir an
